### ISSUE TITLE
Brackets Dark Theme for Nova is using wrong colors.

### ISSUE THREAD

**Issue by danjguzman** [maxgrafik/Brackets.novaextension#1]
First, thanks for this. It made transitioning to Nova from Brackets much easier.

I've noticed something odd when trying to use this theme in Nova, it seemed off. I finally compared it to Brackets itself and noticed the colors are wrong.

Dark Theme in Brackets (purple vars):

![Screen Shot 2021-04-13 at 2 09 13 PM](https://user-images.githubusercontent.com/33531668/114621703-e274d380-9c61-11eb-9fbd-4c8c27a46e9d.png)

Brackets Dark Theme in Nova (white vars are wrong, also inconsistent with some var names such as "label" (blue)):

![Screen Shot 2021-04-13 at 2 09 02 PM](https://user-images.githubusercontent.com/33531668/114621722-e86ab480-9c61-11eb-9ed5-410823951117.png)

The Ad for the Brackets Themes Extension shows the proper colors, but it's not what shows in the actual Nova Editor.

![Screen Shot 2021-04-13 at 2 10 45 PM](https://user-images.githubusercontent.com/33531668/114621887-1cde7080-9c62-11eb-8d8f-ab17434277b9.png)

**Comment by maxgrafik** [comment]
Thanks for bringing this up and providing screenshots. Unfortunately I already deleted Brackets, so I couldn't check everything 😉 
I noticed something similar with the light theme. I'll have a look at it.

**Comment by maxgrafik** [comment]
I think I fixed it with the 1.3 branch. At least for JS and JSX files (hoping I didn't introduce new bugs). TypeScript files still show the wrong colors, because the lexical tokens from the language parser are somewhat wrong here. Could you test the 1.3 branch, please? Or do you want me to push the update to the Nova extension library?

**Comment by danjguzman** [comment]
Since I am pretty new to Nova, and have no idea how to test the 1.3 branch with it, pushing to the Nova Extensions Library would be best. Thanks.

**Comment by maxgrafik** [comment]
No problem. You should see the update in the Nova Extensions Library now. Please let me know, if you find any other bugs.

**Comment by danjguzman** [comment]
Definitely an improvement thank you! 

I did discover other bugs now that the colors have changed, helping to reveal them.

### **In Nova**

Notice that **useLocation, useNavigation** and **dataRaw** are in white, they should be purple. I've noticed that when variables are in lowercase, they are **white** (incorrect), but when capitalized they are **purple** (correct).

![Screen Shot 2021-04-15 at 4 58 01 PM](https://user-images.githubusercontent.com/33531668/114952823-f9efc000-9e0b-11eb-8e7a-739b469b560d.png)

Below is an example of what happens when the same var is all lowercase and capitalized, the correct colors are applied here only when capitalized.

![Screen Shot 2021-04-15 at 4 59 00 PM](https://user-images.githubusercontent.com/33531668/114953082-7b475280-9e0c-11eb-8dc4-fc56bb304bae.png)

**Brackets for comparison**

![Screen Shot 2021-04-15 at 4 54 11 PM](https://user-images.githubusercontent.com/33531668/114953068-7387ae00-9e0c-11eb-85ae-f4d6a295663e.png)

### **TypeScript**

The TypeScript optional parameter "?" causes the key/variable to become white. The var should still be purple with the "?" in white.

In Nova:

![Screen Shot 2021-04-15 at 5 05 20 PM](https://user-images.githubusercontent.com/33531668/114953238-ccefdd00-9e0c-11eb-866f-9bdc1dbc9813.png)

In Brackets:

![Screen Shot 2021-04-15 at 5 34 34 PM](https://user-images.githubusercontent.com/33531668/114955186-eabf4100-9e10-11eb-9eb9-3bfdd0c7f7d5.png)

### **Object Variables**

Currently the Obj Vars (e.g., **_crumb.label_**) shows as blue (incorrect) as seen in Nova:

![Screen Shot 2021-04-15 at 5 13 39 PM](https://user-images.githubusercontent.com/33531668/114954426-67512000-9e0f-11eb-8fdb-e1a203a98625.png)

Seen in Brackets (correct):

![Screen Shot 2021-04-15 at 5 13 32 PM](https://user-images.githubusercontent.com/33531668/114954437-70da8800-9e0f-11eb-85fa-cf80e4cd41d6.png)

### **Comments**

Commenting within JSX with curly braces **{/\* Comment \*/}** highlights the comment text, it should be grayed out since it's a comment.

Nova (incorrect):

![Screen Shot 2021-04-15 at 4 56 08 PM](https://user-images.githubusercontent.com/33531668/114953609-96669200-9e0d-11eb-9a70-1ec69fe91ade.png)

Brackets (correct):

![Screen Shot 2021-04-15 at 4 56 03 PM](https://user-images.githubusercontent.com/33531668/114954063-94510300-9e0e-11eb-842f-8719000da42f.png)

**Comment by danjguzman** [comment]
Additional findings which may be related to Object Variables posted above:

When defining an object, in Nova the colors are inconsistent. 

It still sees "label" as some kind of special variable and colors it blue (incorrect); the Object keys/vars are in white (incorrect); the Object being referenced in the key **component: Components.Person** is also incorrect.

**In Nova:**

![Screen Shot 2021-04-15 at 6 01 24 PM](https://user-images.githubusercontent.com/33531668/114956952-d54c1600-9e14-11eb-9508-304f63bea45d.png)

**In Brackets:**

![Screen Shot 2021-04-15 at 6 01 11 PM](https://user-images.githubusercontent.com/33531668/114956958-d8470680-9e14-11eb-9b09-727631c184ba.png)

**Comment by maxgrafik** [comment]
Thanks for taking the time and giving such a detailed bug report. I looked at it and I'm afraid there's currently absolutely nothing I can do about it. Nova assigns the wrong lexical classes when parsing a file. When you change the syntax mode being applied to the current document (JavaScript, JSX, TypeScript), colors change. Some are correct, some are wrong. It's a flaw in the way Nova tokenizes a given syntax. The built-in themes give the same inconsistent colors. This is something Panic has to fix, as I can only style/theme a given lexical class (e.g. string, constant, function, number, etc.). And for the cases you mentioned above, Nova does not provide the correct lexical class. So sorry 😞

**Comment by danjguzman** [comment]
I understand. Maybe forwarding this ticket to Panic might get them to take a look on their end.

Your Brackets theme appears to be 99% functioning well when I set syntax to **JSX**, and it fixes most issues except for any object key that ends in ".label" which still renders in _blue_ even in JSX.

Overall it's really no big to deal to work under JSX instead of TSX.

Thanks a lot for this, I appreciate the work. It has improved the Nova experience 100%. :)
